dist: focal
language: java
jdk:
- openjdk11
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_bbedb246563f_key -iv $encrypted_bbedb246563f_iv
  -in codesigning.asc.enc -out codesigning.asc -d
- sudo apt-get update
- export GPG_TTY=$(tty) #-> https://github.com/keybase/keybase-issues/issues/2798
- gpg2 --batch --fast-import codesigning.asc
# get parent project
- (if [ $(git ls-remote https://github.com/ant-media/ant-media-server-parent.git $TRAVIS_BRANCH  | wc -l) == "1" ];  
    then 
      echo " $TRAVIS_BRANCH branch found";  
      git clone --depth=1 -b $TRAVIS_BRANCH https://github.com/ant-media/ant-media-server-parent.git;  
    else
      echo "branch not found"; 
      git clone --depth=1 https://github.com/ant-media/ant-media-server-parent.git;  
  fi)
- cd ant-media-server-parent
- mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true --quiet
- cd ..
  
#get server project
- (if [ $(git ls-remote https://github.com/ant-media/Ant-Media-Server.git $TRAVIS_BRANCH  | wc -l) == "1" ];  
    then 
      echo "$TRAVIS_BRANCH branch found in Ant-Media-Server";  
      git clone --depth=1 -b $TRAVIS_BRANCH https://github.com/ant-media/Ant-Media-Server.git;  
    else 
      echo "$TRAVIS_BRANCH branch not found checkout master"; 
      git clone --depth=1 https://github.com/ant-media/Ant-Media-Server.git;  
  fi)
- cd Ant-Media-Server 
- mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true --quiet
- cd ..  #up to Ant-Media-Server 

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V --quiet
script: 
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
- provider: script
  script: mvn deploy -DskipTests --quiet --settings mvn-settings.xml
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: $(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}'
      --non-recursive exec:exec)  = *"SNAPSHOT"*
- provider: script
  script: mvn deploy -DskipTests --quiet --settings mvn-settings.xml
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^ams-v"
